import React, { useEffect, useMemo, useState } from 'react'
import { alertService } from '@/services/alertService'
import { Alert } from '@/types'
import { DetailSheet } from '@/components/common/DetailSheet'
import { Search } from 'lucide-react'

export const AlertsPage = () => { const [alerts,setAlerts]=useState<Alert[]>([]),[filter,setFilter]=useState('Active'),[query,setQuery]=useState(''),[selected,setSelected]=useState<Alert|null>(null)
  useEffect(()=>{alertService.getAllAlerts().then(setAlerts)},[])
  const visible=useMemo(()=>alerts.filter(a=>(filter==='All'||filter==='Active'&&!a.isResolved||filter===a.severity)&&`${a.title} ${a.location}`.toLowerCase().includes(query.toLowerCase())),[alerts,filter,query])
  const resolve=()=>{if(!selected)return;setAlerts(xs=>xs.map(a=>a.id===selected.id?{...a,isResolved:true,resolvedAt:'Just now'}:a));setSelected({...selected,isResolved:true,resolvedAt:'Just now'})}
  return <div className="space-y-6 pb-6"><header className="border-b border-[#DDE6E2] pb-6"><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#075B48]">Incident management</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-[#10231F]">Alarms</h1><p className="mt-2 text-sm text-[#63736E]">Review active conditions, acknowledge the right issue, and keep the incident log clear.</p></header><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-1 rounded-lg bg-[#E8F0ED] p-1">{['Active','CRITICAL','WARNING','All'].map(tab=><button key={tab} onClick={()=>setFilter(tab)} className={`rounded-md px-3 py-1.5 text-xs font-medium ${filter===tab?'bg-white text-[#075B48] shadow-sm':'text-[#63736E]'}`}>{tab}</button>)}</div><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-[#63736E]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search alarms" className="rounded-md border border-[#DDE6E2] py-2 pl-9 pr-3 text-sm outline-none focus:border-[#075B48]" /></label></div><section className="overflow-hidden rounded-xl border border-[#DDE6E2] bg-white">{visible.length?visible.map(a=><button key={a.id} onClick={()=>setSelected(a)} className="grid w-full gap-2 border-b border-[#EDF2F0] p-4 text-left last:border-0 sm:grid-cols-[100px_1fr_180px_130px]"><span className={`text-xs font-semibold ${a.severity==='CRITICAL'?'text-[#C83D3D]':a.severity==='WARNING'?'text-[#D98A00]':'text-[#2386A8]'}`}>● {a.severity}</span><span><b className="block text-sm text-[#10231F]">{a.title}</b><span className="text-xs text-[#63736E]">{a.location}</span></span><span className="text-xs text-[#63736E]">{a.timestamp}</span><span className="text-xs font-medium text-[#63736E]">{a.isResolved?'Resolved':'Unresolved'}</span></button>):<p className="p-10 text-center text-sm text-[#63736E]">No alarms match this filter.</p>}</section>{selected&&<DetailSheet title={selected.title} eyebrow={`${selected.severity} alarm`} onClose={()=>setSelected(null)}><p className="text-sm leading-6 text-[#63736E]">{selected.description}</p><div className="mt-6 rounded-lg bg-[#F7F9F8] p-4 text-sm"><p><b>Location:</b> {selected.location}</p><p className="mt-2"><b>Source:</b> {selected.source}</p><p className="mt-2"><b>Time:</b> {selected.timestamp}</p></div>{!selected.isResolved&&<button onClick={resolve} className="mt-6 rounded-md bg-[#075B48] px-4 py-2.5 text-sm font-medium text-white">Acknowledge alarm</button>}</DetailSheet>}</div> }
